# Generated by Django 5.2.15 on 2026-09-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationia',
            name='methode',
            field=models.CharField(choices=[('XGBOOST', 'XGBoost'), ('HEURISTIQUE', 'Heuristique')], default='HEURISTIQUE', help_text="Methode utilisee pour l'estimation (XGBoost ou heuristique).", max_length=15),
        ),
        migrations.AddField(
            model_name='estimationia',
            name='score_confiance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Score de confiance de l'estimation (0-100 %), pertinent pour XGBoost.", max_digits=5, null=True),
        ),
    ]
