# Generated by Django 5.2.17 on 2026-08-21 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('commandes', '0006_commande_nature_devis_duree_contrat_annees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cout_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Coût unitaire de l'article, utilisé par le moteur de calcul du catalogue (RG27).", max_digits=12),
        ),
        migrations.AddField(
            model_name='devis',
            name='options_ajustees',
            field=models.JSONField(blank=True, default=dict, help_text='Options mineures ajustées au devis (ex. couleur du papier de couverture).'),
        ),
        migrations.AddField(
            model_name='devis',
            name='produit_catalogue',
            field=models.ForeignKey(blank=True, help_text='Produit du catalogue instancié pour ce devis (RG27, mise à jour STI). Laissé vide pour un devis hors catalogue, dont le prix de revient est saisi manuellement.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devis_instancies', to='catalogue.produit'),
        ),
    ]
