# Generated by Django 5.2.15 on 2026-09-03 08:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_produit_date_maj_produit_description_and_more'),
        ('commandes', '0008_lignedevis_article_emplacement_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapeproduction',
            options={'ordering': ['dossier_id', 'ordre', 'id']},
        ),
        migrations.AddField(
            model_name='atelier',
            name='capacite',
            field=models.PositiveIntegerField(default=0, help_text="Capacité horaire de l'atelier (heures par période de référence)."),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_livraison_souhaitee',
            field=models.DateField(blank=True, help_text='Date de livraison souhaitée par le client.', null=True),
        ),
        migrations.AddField(
            model_name='dossierfabrication',
            name='date_cloture',
            field=models.DateTimeField(blank=True, help_text='Date de cloture effective du dossier de fabrication.', null=True),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0, help_text="Ordre d'execution de l'etape dans le dossier."),
        ),
        migrations.AddField(
            model_name='etapeproduction',
            name='poste',
            field=models.ForeignKey(blank=True, help_text='Poste de charge concerne par cette etape.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etapes_production', to='catalogue.postedecharge'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='commentaire',
            field=models.CharField(blank=True, help_text='Commentaire libre sur le mouvement de stock.', max_length=255),
        ),
        migrations.AddField(
            model_name='organismeclient',
            name='contact_principal',
            field=models.CharField(blank=True, help_text="Nom du contact principal chez l'organisme.", max_length=100),
        ),
        migrations.AddField(
            model_name='organismeclient',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organismeclient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organismeclient',
            name='nif_stat',
            field=models.CharField(blank=True, help_text="Numéro d'identification fiscale / statistique.", max_length=30),
        ),
        migrations.AddField(
            model_name='organismeclient',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('RESERVATION', 'Réservation')], max_length=15),
        ),
        migrations.CreateModel(
            name='LigneMatiereDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_estimee', models.DecimalField(decimal_places=3, help_text='Quantité estimée de matière pour ce devis.', max_digits=10)),
                ('unite', models.CharField(blank=True, max_length=20)),
                ('cout_estime', models.DecimalField(decimal_places=2, default=0, help_text='Coût estimé de cette ligne matière (calculé depuis le catalogue).', max_digits=12)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_devis', to='commandes.article')),
                ('ligne_devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_matiere', to='commandes.lignedevis')),
            ],
            options={
                'verbose_name': 'Ligne matière du devis',
                'verbose_name_plural': 'Lignes matière du devis',
                'db_table': 'lignes_matiere_devis',
            },
        ),
        migrations.CreateModel(
            name='LigneOperationDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre_execution', models.PositiveSmallIntegerField(help_text="Rang d'execution de l'operation dans la gamme.")),
                ('temps_estime', models.DecimalField(decimal_places=2, help_text='Temps estimé pour cette opération, en minutes (RG39).', max_digits=8)),
                ('cout_estime', models.DecimalField(decimal_places=2, default=0, help_text='Coût estimé de cette ligne opération (calculé depuis le catalogue).', max_digits=12)),
                ('ligne_devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_operation', to='commandes.lignedevis')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_operation_devis', to='catalogue.postedecharge')),
            ],
            options={
                'verbose_name': 'Ligne opération du devis',
                'verbose_name_plural': 'Lignes opération du devis',
                'db_table': 'lignes_operation_devis',
                'ordering': ['ligne_devis_id', 'ordre_execution'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_reel', models.DecimalField(decimal_places=2, help_text='Temps réellement passé, en minutes (RG35).', max_digits=8)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('EXECUTEE', 'Exécutée')], default='PLANIFIEE', help_text="Statut d'execution de l'operation (RG38).", max_length=15)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions_operation', to='commandes.dossierfabrication')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions_operation', to='catalogue.postedecharge')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions_saisies', to=settings.AUTH_USER_MODEL)),
                ('ligne_operation_devis', models.ForeignKey(blank=True, help_text="Ligne d'operation du devis correspondante (RG39) : reference l'engagement du devis, pas le catalogue generique.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='commandes.ligneoperationdevis')),
            ],
            options={
                'verbose_name': "Exécution d'opération",
                'verbose_name_plural': "Exécutions d'opérations",
                'db_table': 'executions_operation',
                'ordering': ['-date_saisie'],
            },
        ),
        migrations.CreateModel(
            name='OptionDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex. « Pelliculage mat », « Papier couleur couverture ».', max_length=100)),
                ('description', models.TextField(blank=True, help_text="Description detaillee de l'option.")),
                ('surcout_matiere', models.DecimalField(blank=True, decimal_places=2, help_text='Surcoût matière de cette option, le cas échéant (RG33).', max_digits=12, null=True)),
                ('surcout_operation', models.DecimalField(blank=True, decimal_places=2, help_text='Surcoût opération de cette option, le cas échéant (RG33).', max_digits=12, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='commandes.devis')),
            ],
            options={
                'verbose_name': 'Option de devis',
                'verbose_name_plural': 'Options de devis',
                'db_table': 'options_devis',
            },
        ),
    ]
