# Generated by Django 5.2.15 on 2026-09-09

import django.core.validators
from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commandes", "0010_stock_reservations_and_validators"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="article",
                    name="cout_unitaire",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Coût unitaire de l'article, utilisé par le moteur de calcul du catalogue (RG27).",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0")
                            )
                        ],
                    ),
                ),
                migrations.AlterField(
                    model_name="article",
                    name="quantite_stock",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0")
                            )
                        ],
                    ),
                ),
                migrations.AlterField(
                    model_name="article",
                    name="seuil_securite",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Stock de sécurité : seuil en-dessous duquel une alerte est déclenchée.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0")
                            )
                        ],
                    ),
                ),
                migrations.AlterField(
                    model_name="commande",
                    name="quantite",
                    field=models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                    ),
                ),
                migrations.AlterField(
                    model_name="executionoperation",
                    name="temps_reel",
                    field=models.DecimalField(
                        decimal_places=2,
                        help_text="Temps réellement passé, en minutes (RG35).",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.01")
                            )
                        ],
                    ),
                ),
                migrations.AlterField(
                    model_name="lignematieredevis",
                    name="quantite_estimee",
                    field=models.DecimalField(
                        decimal_places=3,
                        help_text="Quantité estimée de matière pour ce devis.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.001")
                            )
                        ],
                    ),
                ),
                migrations.AlterField(
                    model_name="ligneoperationdevis",
                    name="temps_estime",
                    field=models.DecimalField(
                        decimal_places=2,
                        help_text="Temps estimé pour cette opération, en minutes (RG39).",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.01")
                            )
                        ],
                    ),
                ),
                migrations.AlterField(
                    model_name="mouvementstock",
                    name="quantite",
                    field=models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.01")
                            )
                        ],
                    ),
                ),
                migrations.AlterField(
                    model_name="optiondevis",
                    name="surcout_matiere",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Surcoût matière de cette option, le cas échéant (RG33).",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0")
                            )
                        ],
                    ),
                ),
                migrations.AlterField(
                    model_name="optiondevis",
                    name="surcout_operation",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Surcoût opération de cette option, le cas échéant (RG33).",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0")
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]