# Generated by Django 5.2.15 on 2026-09-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0011_alter_article_cout_unitaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
