# Generated by Django 5.2.15 on 2026-09-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='statut_paiement',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYEE', 'Payée'), ('IMPAYEE', 'Impayée')], default='EN_ATTENTE', help_text='Statut de paiement de la facture.', max_length=15),
        ),
    ]
