# Generated by Django 5.2.17 on 2026-08-21 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleprixrevient',
            name='composant',
            field=models.ForeignKey(blank=True, help_text='Composant comparé (prévisionnel/réel) lorsque le dossier est rattaché à un produit du catalogue (RG28, mise à jour STI). Laissé vide pour une comparaison globale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_prix_revient', to='catalogue.composant'),
        ),
    ]
