# Generated by Django 5.2.15 on 2026-09-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_controleprixrevient_composant_par_composant'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleprixrevient',
            name='marge_reelle',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Marge réelle en valeur (part_vente - cout_reel).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='controleprixrevient',
            name='resultat',
            field=models.CharField(choices=[('SOUS_MARGE', 'Sous-marge (déficitaire)'), ('DANS_LA_NORME', 'Dans la norme'), ('SUR_MARGE', 'Sur-marge (surestimation)')], default='DANS_LA_NORME', editable=False, max_length=15),
        ),
    ]
