# Generated by Django 5.2.17 on 2026-08-21 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0006_commande_nature_devis_duree_contrat_annees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(help_text='Rang du composant (1..N).')),
                ('designation', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Composant',
                'verbose_name_plural': 'Composants',
                'db_table': 'composants_produit',
                'ordering': ['produit_id', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='FamilleProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('FEUILLE_VOLANTE', 'Feuille volante'), ('BROCHURE', 'Brochure'), ('MAGAZINE_LIVRE', 'Magazine / Livre / Agenda'), ('CARNET_REGISTRE', 'Carnet de factures / Registre')], max_length=30, unique=True)),
                ('structure_type', models.CharField(blank=True, help_text='Description libre du mode de décomposition attendu pour cette famille.', max_length=30)),
            ],
            options={
                'verbose_name': 'Famille de produits',
                'verbose_name_plural': 'Familles de produits',
                'db_table': 'familles_produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('cout_horaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Machine / Poste',
                'verbose_name_plural': 'Machines / Postes',
                'db_table': 'machines_postes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='LigneMatierePremiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_unitaire', models.DecimalField(decimal_places=3, help_text='Quantité de matière requise par exemplaire produit.', max_digits=10)),
                ('formule_calcul', models.CharField(blank=True, help_text='Formule spécifique pour les cas non strictement linéaires (optionnel).', max_length=255)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_catalogue', to='commandes.article')),
                ('composant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_matiere_premiere', to='catalogue.composant')),
            ],
            options={
                'verbose_name': 'Ligne de matière première',
                'verbose_name_plural': 'Lignes de matière première',
                'db_table': 'lignes_matiere_premiere_composant',
            },
        ),
        migrations.CreateModel(
            name='LigneOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex. impression recto/verso, pliage, piquage, assemblage.', max_length=60)),
                ('temps_unitaire', models.DecimalField(decimal_places=2, help_text='Temps machine requis par exemplaire produit, en minutes.', max_digits=8)),
                ('formule_calcul', models.CharField(blank=True, max_length=255)),
                ('composant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_operation', to='catalogue.composant')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_catalogue', to='catalogue.machine')),
            ],
            options={
                'verbose_name': "Ligne d'opération",
                'verbose_name_plural': "Lignes d'opération",
                'db_table': 'lignes_operation_composant',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('actif', models.BooleanField(default=True, help_text="Un produit désactivé n'apparaît plus dans le choix du devis.")),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='catalogue.familleproduit')),
            ],
            options={
                'verbose_name': 'Produit du catalogue',
                'verbose_name_plural': 'Produits du catalogue',
                'db_table': 'produits_catalogue',
                'ordering': ['famille__nom', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='composant',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composants', to='catalogue.produit'),
        ),
        migrations.AlterUniqueTogether(
            name='composant',
            unique_together={('produit', 'ordre')},
        ),
    ]
