# Generated by Django 5.2.15 on 2026-09-03 08:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_poste_de_charge_charges_fixes_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_maj',
            field=models.DateTimeField(auto_now=True, help_text='Date de derniere modification du produit.'),
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, help_text='Description libre du produit.'),
        ),
        migrations.AddField(
            model_name='produit',
            name='marge_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('30'), help_text='Marge maximale acceptable (en %) — RG36.', max_digits=5),
        ),
        migrations.AddField(
            model_name='produit',
            name='marge_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='Marge minimale acceptable (en %) — RG36.', max_digits=5),
        ),
        migrations.AddField(
            model_name='produit',
            name='reference',
            field=models.CharField(blank=True, help_text='Reference interne du produit (optionnelle).', max_length=30),
        ),
    ]
