# Generated by Django 5.2.15 on 2026-09-09
from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_validateurs_valeurs_numeriques"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="postedecharge",
                    name="cout_horaire",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Coût horaire du poste, utilisé par le moteur de calcul.",
                        max_digits=10,
                    ),
                ),
                migrations.AlterField(
                    model_name="produit",
                    name="marge_min",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10"),
                        help_text="Marge minimale acceptable (en %) — RG36.",
                        max_digits=5,
                    ),
                ),
            ],
        ),
    ]