# Generated by Django 5.2.15 on 2026-09-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_postedecharge_cout_horaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedecharge',
            name='cout_horaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
